Repository WePays/WePay, pull requests merged in 2022-11, with the labels that each got.

#78 externalize configuration and Added some installuction script
  .github/workflows/django.yml
  .gitignore
  README.md
  WePay/config.py
  WePay/models/payment.py
  mysite/settings.py
  sample.env
  setup(dev).sh
  setup.sh
Labels: documentation, enhancement

#136 Fix application freezing during sending mail
  .gitignore
  WePay/models/payment.py
  WePay/payment_urls.py
  WePay/tests/test_.py
  WePay/tests/test_bill.py
  WePay/tests/test_payment.py
  WePay/topic_urls.py
  WePay/utils.py
  WePay/views/__init__.py
  WePay/views/bill.py
  WePay/views/history.py
  WePay/views/payment.py
  WePay/views/topic.py
  WePay/views/userprofile.py
  WePay/whatever.py
  mysite/settings.py
  requirements.txt
  staticfiles/staticfiles.json
  staticfiles/wepay/qr/promptpay5.aaf306fd4ea0.svg
  staticfiles/wepay/qr/promptpay5.aaf306fd4ea0.svg.gz
  staticfiles/wepay/qr/promptpay5.svg
  staticfiles/wepay/qr/promptpay5.svg.gz
  templates/Wepay/Instruction.html
  templates/Wepay/add_topic.html
  templates/Wepay/base.html
  templates/Wepay/create_bills.html
  templates/Wepay/detail.html
  templates/Wepay/history.html
  templates/Wepay/payment.html
  templates/Wepay/payment_detail.html
  templates/Wepay/qr.html
  templates/Wepay/user_profile.html
  templates/socialaccount/authentication_error.html
Labels: enhancement, Refactor

#137 Pop up message
  WePay/models/bill.py
  WePay/tests/test_.py
  WePay/tests/test_bill.py
  WePay/tests/test_e2e_deploy.py
  WePay/tests/test_e2e_local.py
  WePay/views/bill.py
  templates/Wepay/Instruction.html
  templates/Wepay/about.html
  templates/Wepay/base.html
  templates/Wepay/bill.html
  templates/Wepay/detail.html
  templates/Wepay/payment.html
  templates/Wepay/payment_detail.html
  templates/Wepay/qr.html
  templates/Wepay/user_profile.html
  templates/account/base.html
Labels: enhancement, frontend
